#!/bin/bash

export DUNST_WIDTH=350
export DUNST_HEIGHT=200
export DUNST_PADDING=5
export DUNST_HORIZONTAL_PADDING=5
export DUNST_FONT_SIZE=14

export TERMITE_FONT_SIZE=15

export POLYBAR_BAR_HEIGHT=45
export POLYBAR_BAR_TRAY_MAXSIZE=23
export POLYBAR_FONT_0_SIZE=12
export POLYBAR_FONT_1_SCALE=8
export POLYBAR_FONT_2_SIZE=17
export POLYBAR_FONT_3_SIZE=17

export I3_FONT_SIZE=15
export I3_SCRATCHPAD_TERMINAL_SIZE="1200 700"
export I3_SCRATCHPAD_MAXIMUM_FLOATING_SIZE="1200 x 1200"

export FIREFOX_DEV_PIXELS_PER_PX="-1.0"
