#!/bin/bash

export DUNST_WIDTH=420
export DUNST_HEIGHT=240
export DUNST_PADDING=6
export DUNST_HORIZONTAL_PADDING=6
export DUNST_FONT_SIZE=15

export TERMITE_FONT_SIZE=18

export POLYBAR_BAR_HEIGHT=55
export POLYBAR_BAR_TRAY_MAXSIZE=28
export POLYBAR_FONT_0_SIZE=15
export POLYBAR_FONT_1_SCALE=7
export POLYBAR_FONT_2_SIZE=18
export POLYBAR_FONT_3_SIZE=18

export I3_FONT_SIZE=12
export I3_SCRATCHPAD_TERMINAL_SIZE="1428 833"
export I3_SCRATCHPAD_MAXIMUM_FLOATING_SIZE="1680 x 1680"
export I3_GOOGLE_CHROME_SCALE_FACTOR=1.4

export FIREFOX_DEV_PIXELS_PER_PX="1.3"
