#!/bin/bash

export DUNST_WIDTH=700
export DUNST_HEIGHT=400
export DUNST_PADDING=10
export DUNST_HORIZONTAL_PADDING=10
export DUNST_FONT_SIZE=25

export TERMITE_FONT_SIZE=24

export POLYBAR_BAR_HEIGHT=75
export POLYBAR_BAR_TRAY_MAXSIZE=40
export POLYBAR_FONT_0_SIZE=21
export POLYBAR_FONT_1_SCALE=5
export POLYBAR_FONT_2_SIZE=26
export POLYBAR_FONT_3_SIZE=26

export I3_FONT_SIZE=25
export I3_SCRATCHPAD_TERMINAL_SIZE="2040 1190"
export I3_SCRATCHPAD_MAXIMUM_FLOATING_SIZE="2400 x 2400"
export I3_GOOGLE_CHROME_SCALE_FACTOR=2

export FIREFOX_DEV_PIXELS_PER_PX="1.7"
